version: 0.2

phases:
  install:
    commands:
        - echo install Node 12 ...
        - curl -sL https://deb.nodesource.com/setup_12.x | bash -
        - apt install -y nodejs
    prebuild:
      commands:
        - echo install dependences ...
        - npm install --prefix client
    build:
      commands:
        - echo building ...
        - npm run build --prefix client
