version: 0.2

phases:
  install:
    commands:
      - echo install Node 12 ...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo install server dependences ...
      - npm install
  build:
    commands:
      - echo install client dependencies and build static files
      - npm install --prefix client && npm run build --prefix client
      - echo showing path && pwd
      - echo showing files && ls
        
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"

